on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["7.4", "8.0", "8.5", "stable", "current"]
        racket-variant: ["BC", "CS"]
        include:
          - racket-version: "6.6"
          - racket-version: "7.0"
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v0.12
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing kw-utils and its dependencies, including docs
        run: raco pkg install --auto --link --name kw-utils
      - name: Checking dependencies of kw-utils
        run: raco setup --check-pkg-deps --unused-pkg-deps kw-utils
      - name: Testing kw-utils
        run: raco test -p kw-utils
